version: 2

models:
  - name: stg_orders
    columns:
      - name: order_id
        data_tests:
          - unique
          - not_null

  - name: stg_order_items
    columns:
      - name: order_item_id
        data_tests:
          - unique
          - not_null
      - name: order_id
        data_tests:
          - not_null

  - name: fct_sales
    columns:
      - name: order_item_id
        data_tests:
          - unique
          - not_null
      - name: order_id
        data_tests:
          - not_null
      - name: product_id
        data_tests:
          - not_null
